import Head from "next/head"

function Header(){
    return(
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
            <title>Neat NFT | Buy Me Blinks</title>
        </Head>
    )
}

export default Header